# Generated by Django 4.1.7 on 2023-04-11 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FacilityApp', '0001_initial'),
        ('AuthApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('ReviewId', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=300)),
                ('State', models.CharField(max_length=100)),
                ('Destination', models.ForeignKey(max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='FacilityApp.facility')),
                ('Source', models.ForeignKey(max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='AuthApp.citizen')),
            ],
        ),
    ]
