# Generated by Django 4.2 on 2023-04-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('ReviewId', models.AutoField(primary_key=True, serialize=False)),
                ('Source', models.CharField(max_length=300)),
                ('Destination', models.CharField(max_length=300)),
                ('Description', models.CharField(max_length=300)),
            ],
        ),
    ]
