# Generated by Django 4.1.7 on 2023-04-11 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('FacilityId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('facility_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FacilityApp.facility')),
                ('type', models.CharField(max_length=70)),
            ],
            bases=('FacilityApp.facility',),
        ),
    ]
