# Generated by Django 4.1.7 on 2023-05-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilityApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='app',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
