# Generated by Django 4.1.7 on 2023-05-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilityApp', '0002_app_cover_app_description_app_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='cover',
            field=models.URLField(blank=True, null=True),
        ),
    ]
