# Generated by Django 4.2 on 2023-04-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilityApp', '0002_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='Documents',
            field=models.ManyToManyField(null=True, to='FacilityApp.document'),
        ),
    ]
