# Generated by Django 4.2 on 2023-04-12 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilityApp', '0003_document_service_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='Services',
            field=models.ManyToManyField(null=True, to='FacilityApp.service'),
        ),
        migrations.AlterField(
            model_name='app',
            name='rate',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
