# Generated by Django 4.2 on 2023-04-12 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacilityApp', '0004_document_services_alter_app_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='Services',
        ),
    ]
