# Generated by Django 4.2 on 2023-04-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilityApp', '0005_remove_document_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Documents',
            field=models.ManyToManyField(null=True, related_name='services', to='FacilityApp.document'),
        ),
    ]
