# Generated by Django 4.1.7 on 2023-04-11 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(default='test@example.com', max_length=50, unique=True)),
                ('Password', models.CharField(max_length=128)),
                ('Gender', models.CharField(default='male', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AuthApp.user')),
                ('NationalId', models.CharField(max_length=14, null=True)),
                ('PhoneNumber', models.CharField(max_length=11)),
            ],
            bases=('AuthApp.user',),
        ),
        migrations.CreateModel(
            name='GovSupervisor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AuthApp.user')),
                ('GovId', models.CharField(max_length=100, unique=True)),
                ('GovAgencyName', models.CharField(max_length=100)),
            ],
            bases=('AuthApp.user',),
        ),
        migrations.CreateModel(
            name='AgencySupervisor',
            fields=[
                ('govsupervisor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AuthApp.govsupervisor')),
                ('AgencyName', models.CharField(max_length=100, unique=True)),
            ],
            bases=('AuthApp.govsupervisor',),
        ),
        migrations.CreateModel(
            name='BranchSupervisor',
            fields=[
                ('govsupervisor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AuthApp.govsupervisor')),
                ('BranchName', models.CharField(max_length=100, unique=True)),
            ],
            bases=('AuthApp.govsupervisor',),
        ),
    ]
