# Generated by Django 4.2 on 2023-04-29 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AuthApp.user')),
                ('nationalId', models.CharField(max_length=14, null=True)),
                ('email', models.EmailField(default='test@example.com', max_length=50, unique=True)),
                ('phoneNumber', models.CharField(max_length=11)),
            ],
            bases=('AuthApp.user',),
        ),
        migrations.CreateModel(
            name='GovSupervisor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AuthApp.user')),
                ('govId', models.CharField(max_length=100, unique=True)),
                ('supervisionType', models.CharField(max_length=100)),
            ],
            bases=('AuthApp.user',),
        ),
        migrations.CreateModel(
            name='AgencySupervisor',
            fields=[
                ('govsupervisor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AuthApp.govsupervisor')),
                ('agencyName', models.CharField(max_length=100, unique=True)),
            ],
            bases=('AuthApp.govsupervisor',),
        ),
        migrations.CreateModel(
            name='BranchSupervisor',
            fields=[
                ('govsupervisor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AuthApp.govsupervisor')),
                ('branchName', models.CharField(max_length=100, unique=True)),
            ],
            bases=('AuthApp.govsupervisor',),
        ),
    ]
