# Generated by Django 4.1.7 on 2023-03-21 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovSupervisor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AuthApp.user')),
                ('GovId', models.CharField(default='2023', max_length=100)),
                ('GovAgencyName', models.CharField(default='xyz', max_length=100)),
            ],
            bases=('AuthApp.user',),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='PhoneNumber',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(max_length=128),
        ),
    ]
