# Generated by Django 4.2 on 2023-04-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Gender',
        ),
        migrations.AddField(
            model_name='citizen',
            name='Email',
            field=models.EmailField(default='test@example.com', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='citizen',
            name='Gender',
            field=models.CharField(default='male', max_length=100),
        ),
    ]
