# Generated by Django 4.1.7 on 2023-03-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0002_govsupervisor_alter_citizen_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govsupervisor',
            name='GovAgencyName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='govsupervisor',
            name='GovId',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(default='test@example.com', max_length=50, unique=True),
        ),
    ]
