# Generated by Django 4.1.7 on 2023-03-21 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0003_alter_govsupervisor_govagencyname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencySupervisor',
            fields=[
                ('govsupervisor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AuthApp.govsupervisor')),
                ('AgencyName', models.CharField(max_length=100, unique=True)),
            ],
            bases=('AuthApp.govsupervisor',),
        ),
        migrations.CreateModel(
            name='BranchSupervisor',
            fields=[
                ('govsupervisor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AuthApp.govsupervisor')),
                ('BranchName', models.CharField(max_length=100, unique=True)),
            ],
            bases=('AuthApp.govsupervisor',),
        ),
    ]
