# Generated by Django 4.2 on 2023-04-13 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AuthApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AuthApp.user')),
                ('AdminId', models.CharField(max_length=10, unique=True)),
            ],
            bases=('AuthApp.user',),
        ),
    ]
